namespace Modern.Lab.Samples
{
    public partial class EquipmentLotForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.titlePanel = new System.Windows.Forms.Panel();
            this.lblTitle = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.spTitle = new System.Windows.Forms.Panel();
            this.searchCard = new Modern.Lab.WinForms.Controls.Layout.ModernCardPanel();
            this.lblGroup = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.cboGroup = new Modern.Lab.WinForms.Controls.Selection.ModernComboBox();
            this.badgeCountdown = new Modern.Lab.WinForms.Controls.Display.ModernStatusBadge();
            this.lblInterval = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.cboInterval = new Modern.Lab.WinForms.Controls.Selection.ModernComboBox();
            this.btnRefresh = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.menuEqp = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.menuPort = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.menuLot = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.gapSearch = new System.Windows.Forms.Panel();
            this.midPanel = new System.Windows.Forms.Panel();
            this.splitMain = new Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer();
            this.splitLeft = new Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer();
            this.splitLotRequest = new Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer();
            this.eqpCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.gridEqp = new Modern.Lab.WinForms.Controls.Data.ModernDataGrid();
            this.portCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.gridPorts = new Modern.Lab.WinForms.Controls.Data.ModernDataGrid();
            this.splitRight = new Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer();
            this.splitDurableDecision = new Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer();
            this.lotCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.gridLots = new Modern.Lab.WinForms.Controls.Data.ModernDataGrid();
            this.requestCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.splitRequest = new Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer();
            this.tableRequestMaster = new System.Windows.Forms.TableLayoutPanel();
            this.fieldRequest = new Modern.Lab.WinForms.Controls.Display.ModernFieldList();
            this.panelRequestRemark = new System.Windows.Forms.Panel();
            this.lblRequestRemarkCaption = new System.Windows.Forms.Label();
            this.lblRequestRemark = new System.Windows.Forms.Label();
            this.lblRequestEmpty = new System.Windows.Forms.Label();
            this.gridSpecimens = new Modern.Lab.WinForms.Controls.Data.ModernDataGrid();
            this.durableCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.gridDurables = new Modern.Lab.WinForms.Controls.Data.ModernDataGrid();
            this.decisionCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.decisionBusy = new Modern.Lab.WinForms.Controls.Display.ModernBusyOverlay();
            this.decisionGrid = new System.Windows.Forms.TableLayoutPanel();
            this.kpiEquipment = new Modern.Lab.WinForms.Controls.Display.ModernKpiCard();
            this.kpiPorts = new Modern.Lab.WinForms.Controls.Display.ModernKpiCard();
            this.kpiLot = new Modern.Lab.WinForms.Controls.Display.ModernKpiCard();
            this.kpiDurable = new Modern.Lab.WinForms.Controls.Display.ModernKpiCard();
            this.decisionBar = new System.Windows.Forms.Panel();
            this.badgeMode = new Modern.Lab.WinForms.Controls.Display.ModernStatusBadge();
            this.badgeJob = new Modern.Lab.WinForms.Controls.Display.ModernStatusBadge();
            this.btnLock = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.jobActions = new System.Windows.Forms.TableLayoutPanel();
            this.gapActions = new System.Windows.Forms.Panel();
            this.gapJob = new System.Windows.Forms.Panel();
            this.actionCard = new Modern.Lab.WinForms.Controls.Layout.ModernCardPanel();
            this.lblTarget = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.ddbEquipment = new Modern.Lab.WinForms.Controls.Input.ModernDropDownButton();
            this.ddbPort = new Modern.Lab.WinForms.Controls.Input.ModernDropDownButton();
            this.jobCard = new Modern.Lab.WinForms.Controls.Layout.ModernCardPanel();
            this.btnJobPrep = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.btnJobStart = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.btnJobEnd = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.titlePanel.SuspendLayout();
            this.searchCard.SuspendLayout();
            this.midPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitMain)).BeginInit();
            this.splitMain.Panel1.SuspendLayout();
            this.splitMain.Panel2.SuspendLayout();
            this.splitMain.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitLeft)).BeginInit();
            this.splitLeft.Panel1.SuspendLayout();
            this.splitLeft.Panel2.SuspendLayout();
            this.splitLeft.SuspendLayout();
            this.eqpCard.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitLotRequest)).BeginInit();
            this.splitLotRequest.Panel1.SuspendLayout();
            this.splitLotRequest.Panel2.SuspendLayout();
            this.splitLotRequest.SuspendLayout();
            this.lotCard.SuspendLayout();
            this.requestCard.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitRequest)).BeginInit();
            this.splitRequest.Panel1.SuspendLayout();
            this.splitRequest.Panel2.SuspendLayout();
            this.splitRequest.SuspendLayout();
            this.tableRequestMaster.SuspendLayout();
            this.panelRequestRemark.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitRight)).BeginInit();
            this.splitRight.Panel1.SuspendLayout();
            this.splitRight.Panel2.SuspendLayout();
            this.splitRight.SuspendLayout();
            this.portCard.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitDurableDecision)).BeginInit();
            this.splitDurableDecision.Panel1.SuspendLayout();
            this.splitDurableDecision.Panel2.SuspendLayout();
            this.splitDurableDecision.SuspendLayout();
            this.jobCard.SuspendLayout();
            this.durableCard.SuspendLayout();
            this.decisionCard.SuspendLayout();
            this.decisionGrid.SuspendLayout();
            this.decisionBar.SuspendLayout();
            this.jobActions.SuspendLayout();
            this.actionCard.SuspendLayout();
            this.SuspendLayout();
            this.titlePanel.Controls.Add(this.lblTitle);
            this.titlePanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.titlePanel.Location = new System.Drawing.Point(12, 12);
            this.titlePanel.Name = "titlePanel";
            this.titlePanel.Size = new System.Drawing.Size(1776, 28);
            this.titlePanel.TabIndex = 0;
            this.lblTitle.BackColor = System.Drawing.Color.Transparent;
            this.lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitle.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Title;
            this.lblTitle.Location = new System.Drawing.Point(0, 0);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(1776, 28);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Equipment / Lots";
            this.lblTitle.TitleBar = true;
            this.spTitle.Dock = System.Windows.Forms.DockStyle.Top;
            this.spTitle.Location = new System.Drawing.Point(12, 40);
            this.spTitle.Name = "spTitle";
            this.spTitle.Size = new System.Drawing.Size(1776, 8);
            this.spTitle.TabIndex = 1;
            this.searchCard.Controls.Add(this.lblGroup);
            this.searchCard.Controls.Add(this.cboGroup);
            this.searchCard.Controls.Add(this.badgeCountdown);
            this.searchCard.Controls.Add(this.lblInterval);
            this.searchCard.Controls.Add(this.cboInterval);
            this.searchCard.Controls.Add(this.btnRefresh);
            this.searchCard.Dock = System.Windows.Forms.DockStyle.Top;
            this.searchCard.Location = new System.Drawing.Point(12, 48);
            this.searchCard.Name = "searchCard";
            this.searchCard.Padding = new System.Windows.Forms.Padding(12, 8, 12, 8);
            this.searchCard.Size = new System.Drawing.Size(1776, 56);
            this.searchCard.TabIndex = 2;
            this.lblGroup.BackColor = System.Drawing.Color.Transparent;
            this.lblGroup.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Label;
            this.lblGroup.Location = new System.Drawing.Point(12, 12);
            this.lblGroup.Name = "lblGroup";
            this.lblGroup.Size = new System.Drawing.Size(76, 32);
            this.lblGroup.TabIndex = 0;
            this.lblGroup.Text = "Eqp Group";
            this.cboGroup.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboGroup.Location = new System.Drawing.Point(92, 12);
            this.cboGroup.Name = "cboGroup";
            this.cboGroup.Size = new System.Drawing.Size(240, 32);
            this.cboGroup.TabIndex = 1;
            this.cboGroup.SelectedIndexChanged += new System.EventHandler(this.OnGroupChanged);
            this.cboGroup.Child = null;
            this.badgeCountdown.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.badgeCountdown.Location = new System.Drawing.Point(1312, 14);
            this.badgeCountdown.Name = "badgeCountdown";
            this.badgeCountdown.Semantic = Modern.Lab.Theming.SemanticKind.Warning;
            this.badgeCountdown.Shape = Modern.Lab.WinForms.Controls.Display.BadgeShape.Rounded;
            this.badgeCountdown.Size = new System.Drawing.Size(136, 28);
            this.badgeCountdown.TabIndex = 2;
            this.badgeCountdown.Text = "-";
            this.badgeCountdown.Visible = false;
            this.badgeCountdown.Child = null;
            this.lblInterval.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lblInterval.BackColor = System.Drawing.Color.Transparent;
            this.lblInterval.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Label;
            this.lblInterval.Location = new System.Drawing.Point(1456, 12);
            this.lblInterval.Name = "lblInterval";
            this.lblInterval.Size = new System.Drawing.Size(88, 32);
            this.lblInterval.TabIndex = 3;
            this.lblInterval.Text = "Auto refresh";
            this.cboInterval.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.cboInterval.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboInterval.Location = new System.Drawing.Point(1548, 12);
            this.cboInterval.Name = "cboInterval";
            this.cboInterval.Size = new System.Drawing.Size(100, 32);
            this.cboInterval.TabIndex = 4;
            this.cboInterval.SelectedIndexChanged += new System.EventHandler(this.OnIntervalChanged);
            this.cboInterval.Child = null;
            this.btnRefresh.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnRefresh.BackColor = System.Drawing.Color.Transparent;
            this.btnRefresh.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnRefresh.IconGlyph = "\uE72C";
            this.btnRefresh.Location = new System.Drawing.Point(1660, 12);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.Size = new System.Drawing.Size(104, 32);
            this.btnRefresh.TabIndex = 5;
            this.btnRefresh.Text = "Refresh";
            this.btnRefresh.Click += new System.EventHandler(this.OnRefreshClick);
            this.menuEqp.Name = "menuEqp";
            this.menuEqp.Size = new System.Drawing.Size(61, 4);
            this.menuEqp.Opening += new System.ComponentModel.CancelEventHandler(this.OnMenuEqpOpening);
            this.menuPort.Name = "menuPort";
            this.menuPort.Size = new System.Drawing.Size(61, 4);
            this.menuPort.Opening += new System.ComponentModel.CancelEventHandler(this.OnMenuPortOpening);
            this.menuLot.Name = "menuLot";
            this.menuLot.Size = new System.Drawing.Size(61, 4);
            this.menuLot.Opening += new System.ComponentModel.CancelEventHandler(this.OnMenuLotOpening);
            this.gapSearch.Dock = System.Windows.Forms.DockStyle.Top;
            this.gapSearch.Location = new System.Drawing.Point(12, 104);
            this.gapSearch.Name = "gapSearch";
            this.gapSearch.Size = new System.Drawing.Size(1776, 8);
            this.gapSearch.TabIndex = 3;
            this.midPanel.Controls.Add(this.splitRight);
            this.midPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.midPanel.Location = new System.Drawing.Point(12, 112);
            this.midPanel.Name = "midPanel";
            this.midPanel.Size = new System.Drawing.Size(1776, 876);
            this.midPanel.TabIndex = 4;
            this.splitMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitMain.Location = new System.Drawing.Point(0, 0);
            this.splitMain.Name = "splitMain";
            this.splitMain.Orientation = System.Windows.Forms.Orientation.Vertical;
            this.splitMain.Panel1.Controls.Add(this.splitLeft);
            this.splitMain.Panel1MinSize = 520;
            this.splitMain.Panel2.Controls.Add(this.splitLotRequest);
            this.splitMain.Panel2.Padding = new System.Windows.Forms.Padding(0);
            this.splitMain.Panel2MinSize = 360;
            this.splitMain.Size = new System.Drawing.Size(1356, 876);
            this.splitMain.SplitterDistance = 852;
            this.splitMain.SplitterWidth = 8;
            this.splitMain.KeepRatio = true;
            this.splitMain.TabIndex = 0;
            this.splitMain.TabStop = false;
            this.splitLeft.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitLeft.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.splitLeft.Location = new System.Drawing.Point(0, 0);
            this.splitLeft.Name = "splitLeft";
            this.splitLeft.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.splitLeft.Panel1.Controls.Add(this.eqpCard);
            this.splitLeft.Panel1MinSize = 120;
            this.splitLeft.Panel2.Controls.Add(this.lotCard);
            this.splitLeft.Panel2.Padding = new System.Windows.Forms.Padding(0);
            this.splitLeft.Panel2MinSize = 300;
            this.splitLeft.Size = new System.Drawing.Size(852, 876);
            this.splitLeft.SplitterDistance = 282;
            this.splitLeft.SplitterWidth = 8;
            this.splitLeft.TabIndex = 0;
            this.splitLeft.TabStop = false;
            this.splitLeft.SplitterMoved += new System.Windows.Forms.SplitterEventHandler(this.OnListSplitterMoved);
            this.eqpCard.Controls.Add(this.gridEqp);
            this.eqpCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.eqpCard.Location = new System.Drawing.Point(0, 0);
            this.eqpCard.Name = "eqpCard";
            this.eqpCard.Padding = new System.Windows.Forms.Padding(6, 40, 6, 6);
            this.eqpCard.Size = new System.Drawing.Size(852, 282);
            this.eqpCard.TabIndex = 0;
            this.eqpCard.Text = "Equipment List";
            this.eqpCard.TitleBar = true;
            this.gridEqp.AutoFitColumns = true;
            this.gridEqp.ContextMenuStrip = this.menuEqp;
            this.gridEqp.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridEqp.EmptyText = "No equipment in this group";
            this.gridEqp.Location = new System.Drawing.Point(6, 40);
            this.gridEqp.Name = "gridEqp";
            this.gridEqp.ShowExportMenu = false;
            this.gridEqp.ShowStatusBar = true;
            this.gridEqp.Size = new System.Drawing.Size(840, 236);
            this.gridEqp.StatusCountFormat = "{0:N0} equipment";
            this.gridEqp.TabIndex = 0;
            this.gridEqp.RowDoubleClick += new System.EventHandler(this.OnEqpRowDoubleClick);
            this.gridEqp.SelectionChanged += new System.EventHandler(this.OnEqpSelectionChanged);
            this.gridEqp.CellCheckChanged += new System.EventHandler<Modern.Lab.Controls.Wpf.Data.GridCheckChangedEventArgs>(this.OnEqpCellCheckChanged);
            this.gridEqp.Child = null;
            this.splitLotRequest.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitLotRequest.Location = new System.Drawing.Point(0, 0);
            this.splitLotRequest.Name = "splitLotRequest";
            this.splitLotRequest.Panel1.Controls.Add(this.portCard);
            this.splitLotRequest.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.splitLotRequest.Panel1MinSize = 120;
            this.splitLotRequest.Panel2.Controls.Add(this.requestCard);
            this.splitLotRequest.Panel2.Padding = new System.Windows.Forms.Padding(0);
            this.splitLotRequest.Panel2MinSize = 300;
            this.splitLotRequest.Size = new System.Drawing.Size(496, 876);
            this.splitLotRequest.SplitterDistance = 282;
            this.splitLotRequest.SplitterWidth = 8;
            this.splitLotRequest.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.splitLotRequest.TabIndex = 0;
            this.splitLotRequest.TabStop = false;
            this.splitLotRequest.SplitterMoved += new System.Windows.Forms.SplitterEventHandler(this.OnListSplitterMoved);
            this.lotCard.Controls.Add(this.gridLots);
            this.lotCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lotCard.Location = new System.Drawing.Point(0, 0);
            this.lotCard.Name = "lotCard";
            this.lotCard.Padding = new System.Windows.Forms.Padding(6, 40, 6, 6);
            this.lotCard.Size = new System.Drawing.Size(852, 586);
            this.lotCard.TabIndex = 0;
            this.lotCard.Text = "Lot List";
            this.lotCard.TitleBar = true;
            this.gridLots.AutoFitColumns = true;
            this.gridLots.ContextMenuStrip = this.menuLot;
            this.gridLots.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridLots.EmptyText = "No lot to work in this group";
            this.gridLots.Location = new System.Drawing.Point(6, 40);
            this.gridLots.Name = "gridLots";
            this.gridLots.ShowStatusBar = true;
            this.gridLots.Size = new System.Drawing.Size(840, 540);
            this.gridLots.StatusCountFormat = "{0:N0} lots";
            this.gridLots.TabIndex = 0;
            this.gridLots.RowDoubleClick += new System.EventHandler(this.OnLotRowDoubleClick);
            this.gridLots.SelectionChanged += new System.EventHandler(this.OnLotSelectionChanged);
            this.gridLots.Child = null;
            this.splitDurableDecision.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitDurableDecision.FixedPanel = System.Windows.Forms.FixedPanel.Panel2;
            this.splitDurableDecision.Location = new System.Drawing.Point(0, 0);
            this.splitDurableDecision.Name = "splitDurableDecision";
            this.splitDurableDecision.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.splitDurableDecision.Panel1.Controls.Add(this.durableCard);
            this.splitDurableDecision.Panel1MinSize = 80;
            this.splitDurableDecision.Panel2.Controls.Add(this.decisionCard);
            this.splitDurableDecision.Panel2.Padding = new System.Windows.Forms.Padding(0);
            this.splitDurableDecision.Panel2MinSize = 262;
            this.splitDurableDecision.Size = new System.Drawing.Size(412, 876);
            this.splitDurableDecision.SplitterDistance = 640;
            this.splitDurableDecision.SplitterWidth = 8;
            this.splitDurableDecision.TabIndex = 0;
            this.splitDurableDecision.TabStop = false;
            this.splitDurableDecision.SplitterMoved += new System.Windows.Forms.SplitterEventHandler(this.OnDecisionSplitterMoved);
            this.durableCard.Controls.Add(this.gridDurables);
            this.durableCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.durableCard.Location = new System.Drawing.Point(0, 0);
            this.durableCard.Name = "durableCard";
            this.durableCard.Padding = new System.Windows.Forms.Padding(6, 40, 6, 6);
            this.durableCard.Size = new System.Drawing.Size(412, 640);
            this.durableCard.TabIndex = 0;
            this.durableCard.Text = "Durable List (Target)";
            this.durableCard.TitleBar = true;
            this.gridDurables.AutoFitColumns = true;
            this.gridDurables.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridDurables.EmptyText = "No durable for this group";
            this.gridDurables.Location = new System.Drawing.Point(6, 40);
            this.gridDurables.Name = "gridDurables";
            this.gridDurables.ShowExportMenu = false;
            this.gridDurables.ShowStatusBar = true;
            this.gridDurables.Size = new System.Drawing.Size(400, 522);
            this.gridDurables.StatusCountFormat = "{0:N0} durables";
            this.gridDurables.TabIndex = 0;
            this.gridDurables.RowDoubleClick += new System.EventHandler(this.OnDurableRowDoubleClick);
            this.gridDurables.Child = null;
            this.requestCard.Controls.Add(this.splitRequest);
            this.requestCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.requestCard.Location = new System.Drawing.Point(0, 0);
            this.requestCard.Name = "requestCard";
            this.requestCard.Padding = new System.Windows.Forms.Padding(6, 40, 6, 6);
            this.requestCard.Size = new System.Drawing.Size(496, 586);
            this.requestCard.TabIndex = 0;
            this.requestCard.Text = "Request List";
            this.requestCard.TitleBar = true;
            this.splitRequest.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitRequest.FixedPanel = System.Windows.Forms.FixedPanel.Panel1;
            this.splitRequest.Location = new System.Drawing.Point(6, 40);
            this.splitRequest.Name = "splitRequest";
            this.splitRequest.Orientation = System.Windows.Forms.Orientation.Horizontal;
            this.splitRequest.Panel1.AutoScroll = true;
            this.splitRequest.Panel1.Controls.Add(this.tableRequestMaster);
            this.splitRequest.Panel1.Controls.Add(this.lblRequestEmpty);
            this.splitRequest.Panel1MinSize = 100;
            this.splitRequest.Panel2.Controls.Add(this.gridSpecimens);
            this.splitRequest.Panel2.Padding = new System.Windows.Forms.Padding(0);
            this.splitRequest.Panel2MinSize = 40;
            this.splitRequest.Size = new System.Drawing.Size(484, 540);
            this.splitRequest.SplitterDistance = 192;
            this.splitRequest.SplitterWidth = 8;
            this.splitRequest.TabIndex = 0;
            this.splitRequest.TabStop = false;
            this.tableRequestMaster.ColumnCount = 1;
            this.tableRequestMaster.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableRequestMaster.Controls.Add(this.fieldRequest, 0, 0);
            this.tableRequestMaster.Controls.Add(this.panelRequestRemark, 0, 1);
            this.tableRequestMaster.Dock = System.Windows.Forms.DockStyle.Top;
            this.tableRequestMaster.Location = new System.Drawing.Point(0, 0);
            this.tableRequestMaster.Margin = new System.Windows.Forms.Padding(0);
            this.tableRequestMaster.Name = "tableRequestMaster";
            this.tableRequestMaster.RowCount = 2;
            this.tableRequestMaster.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 80F));
            this.tableRequestMaster.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 72F));
            this.tableRequestMaster.Size = new System.Drawing.Size(484, 152);
            this.tableRequestMaster.TabIndex = 0;
            this.tableRequestMaster.Visible = false;
            this.fieldRequest.Columns = 3;
            this.fieldRequest.Dock = System.Windows.Forms.DockStyle.Fill;
            this.fieldRequest.Location = new System.Drawing.Point(0, 0);
            this.fieldRequest.Margin = new System.Windows.Forms.Padding(0);
            this.fieldRequest.Name = "fieldRequest";
            this.fieldRequest.Size = new System.Drawing.Size(484, 80);
            this.fieldRequest.TabIndex = 0;
            this.panelRequestRemark.Controls.Add(this.lblRequestRemark);
            this.panelRequestRemark.Controls.Add(this.lblRequestRemarkCaption);
            this.panelRequestRemark.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelRequestRemark.Location = new System.Drawing.Point(0, 80);
            this.panelRequestRemark.Margin = new System.Windows.Forms.Padding(0);
            this.panelRequestRemark.Name = "panelRequestRemark";
            this.panelRequestRemark.Padding = new System.Windows.Forms.Padding(0, 4, 0, 4);
            this.panelRequestRemark.Size = new System.Drawing.Size(484, 72);
            this.panelRequestRemark.TabIndex = 1;
            this.lblRequestRemarkCaption.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblRequestRemarkCaption.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.lblRequestRemarkCaption.Location = new System.Drawing.Point(10, 4);
            this.lblRequestRemarkCaption.Name = "lblRequestRemarkCaption";
            this.lblRequestRemarkCaption.Size = new System.Drawing.Size(464, 18);
            this.lblRequestRemarkCaption.TabIndex = 0;
            this.lblRequestRemarkCaption.Text = "Remarks";
            this.lblRequestRemark.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRequestRemark.Location = new System.Drawing.Point(10, 22);
            this.lblRequestRemark.Name = "lblRequestRemark";
            this.lblRequestRemark.Size = new System.Drawing.Size(464, 42);
            this.lblRequestRemark.TabIndex = 1;
            this.lblRequestRemark.Text = "-";
            this.lblRequestRemark.TextAlign = System.Drawing.ContentAlignment.TopLeft;
            this.lblRequestRemark.UseMnemonic = false;
            this.lblRequestEmpty.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRequestEmpty.Name = "lblRequestEmpty";
            this.lblRequestEmpty.Text = "Select a lot";
            this.lblRequestEmpty.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.gridSpecimens.AllowFindPanel = false;
            this.gridSpecimens.AutoFitColumns = true;
            this.gridSpecimens.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridSpecimens.EmptyText = "No specimen on this request";
            this.gridSpecimens.Location = new System.Drawing.Point(0, 0);
            this.gridSpecimens.Name = "gridSpecimens";
            this.gridSpecimens.ShowExportMenu = false;
            this.gridSpecimens.ShowStatusBar = true;
            this.gridSpecimens.Size = new System.Drawing.Size(484, 40);
            this.gridSpecimens.StatusCountFormat = "{0:N0} specimens";
            this.gridSpecimens.TabIndex = 1;
            this.gridSpecimens.Child = null;
            this.splitRight.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitRight.FixedPanel = System.Windows.Forms.FixedPanel.Panel2;
            this.splitRight.Location = new System.Drawing.Point(0, 0);
            this.splitRight.Name = "splitRight";
            this.splitRight.Orientation = System.Windows.Forms.Orientation.Vertical;
            this.splitRight.Panel1.Controls.Add(this.splitMain);
            this.splitRight.Panel1.Controls.Add(this.gapActions);
            this.splitRight.Panel1.Controls.Add(this.actionCard);
            this.splitRight.Panel1MinSize = 880;
            this.splitRight.Panel2.Controls.Add(this.splitDurableDecision);
            this.splitRight.Panel2.Controls.Add(this.gapJob);
            this.splitRight.Panel2.Controls.Add(this.jobCard);
            this.splitRight.Panel2.Padding = new System.Windows.Forms.Padding(0);
            this.splitRight.Panel2MinSize = 320;
            this.splitRight.Size = new System.Drawing.Size(1776, 876);
            this.splitRight.SplitterDistance = 1356;
            this.splitRight.SplitterWidth = 8;
            this.splitRight.TabIndex = 0;
            this.splitRight.TabStop = false;
            this.portCard.Controls.Add(this.gridPorts);
            this.portCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.portCard.Location = new System.Drawing.Point(0, 0);
            this.portCard.Name = "portCard";
            this.portCard.Padding = new System.Windows.Forms.Padding(6, 40, 6, 6);
            this.portCard.Size = new System.Drawing.Size(496, 282);
            this.portCard.TabIndex = 0;
            this.portCard.Text = "Port List";
            this.portCard.TitleBar = true;
            this.gridPorts.AllowFindPanel = false;
            this.gridPorts.AutoFitColumns = true;
            this.gridPorts.ContextMenuStrip = this.menuPort;
            this.gridPorts.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridPorts.EmptyText = "Decide an equipment";
            this.gridPorts.Location = new System.Drawing.Point(6, 40);
            this.gridPorts.Name = "gridPorts";
            this.gridPorts.ShowExportMenu = false;
            this.gridPorts.ShowStatusBar = true;
            this.gridPorts.StatusCountFormat = "{0:N0} ports";
            this.gridPorts.Size = new System.Drawing.Size(484, 236);
            this.gridPorts.TabIndex = 0;
            this.gridPorts.RowDoubleClick += new System.EventHandler(this.OnPortRowDoubleClick);
            this.gridPorts.SelectionChanged += new System.EventHandler(this.OnPortSelectionChanged);
            this.gridPorts.Child = null;
            this.decisionCard.Controls.Add(this.decisionBusy);
            this.decisionCard.Controls.Add(this.decisionGrid);
            this.decisionCard.Controls.Add(this.decisionBar);
            this.decisionCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.decisionCard.Location = new System.Drawing.Point(0, 0);
            this.decisionCard.Name = "decisionCard";
            this.decisionCard.Padding = new System.Windows.Forms.Padding(6, 40, 6, 6);
            this.decisionCard.Size = new System.Drawing.Size(412, 262);
            this.decisionCard.TabIndex = 0;
            this.decisionCard.Text = "Decision";
            this.decisionCard.TitleBar = true;
            this.decisionBusy.Location = new System.Drawing.Point(110, 70);
            this.decisionBusy.Message = "Loading decision...";
            this.decisionBusy.Name = "decisionBusy";
            this.decisionBusy.Size = new System.Drawing.Size(300, 120);
            this.decisionBusy.TabIndex = 2;
            this.decisionBusy.Visible = false;
            this.decisionBusy.Child = null;
            this.decisionGrid.ColumnCount = 2;
            this.decisionGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.decisionGrid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.decisionGrid.Controls.Add(this.kpiEquipment, 0, 0);
            this.decisionGrid.Controls.Add(this.kpiPorts, 1, 0);
            this.decisionGrid.Controls.Add(this.kpiLot, 0, 1);
            this.decisionGrid.Controls.Add(this.kpiDurable, 1, 1);
            this.decisionGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.decisionGrid.Location = new System.Drawing.Point(6, 40);
            this.decisionGrid.Name = "decisionGrid";
            this.decisionGrid.RowCount = 2;
            this.decisionGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.decisionGrid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.decisionGrid.Size = new System.Drawing.Size(400, 176);
            this.decisionGrid.TabIndex = 0;
            this.kpiEquipment.Dock = System.Windows.Forms.DockStyle.Fill;
            this.kpiEquipment.Location = new System.Drawing.Point(4, 4);
            this.kpiEquipment.Margin = new System.Windows.Forms.Padding(4);
            this.kpiEquipment.Name = "kpiEquipment";
            this.kpiEquipment.Size = new System.Drawing.Size(246, 96);
            this.kpiEquipment.TabIndex = 0;
            this.kpiEquipment.Title = "Equipment";
            this.kpiEquipment.Value = "-";
            this.kpiPorts.Dock = System.Windows.Forms.DockStyle.Fill;
            this.kpiPorts.Location = new System.Drawing.Point(258, 4);
            this.kpiPorts.Margin = new System.Windows.Forms.Padding(4);
            this.kpiPorts.Name = "kpiPorts";
            this.kpiPorts.Size = new System.Drawing.Size(246, 96);
            this.kpiPorts.TabIndex = 1;
            this.kpiPorts.Title = "In Port → Out Port";
            this.kpiPorts.Value = "-";
            this.kpiLot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.kpiLot.Location = new System.Drawing.Point(4, 108);
            this.kpiLot.Margin = new System.Windows.Forms.Padding(4);
            this.kpiLot.Name = "kpiLot";
            this.kpiLot.Size = new System.Drawing.Size(246, 96);
            this.kpiLot.TabIndex = 2;
            this.kpiLot.Title = "Lot";
            this.kpiLot.Value = "-";
            this.kpiDurable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.kpiDurable.Location = new System.Drawing.Point(258, 108);
            this.kpiDurable.Margin = new System.Windows.Forms.Padding(4);
            this.kpiDurable.Name = "kpiDurable";
            this.kpiDurable.Size = new System.Drawing.Size(246, 96);
            this.kpiDurable.TabIndex = 3;
            this.kpiDurable.Title = "Durable";
            this.kpiDurable.Value = "-";
            this.decisionBar.Controls.Add(this.badgeMode);
            this.decisionBar.Controls.Add(this.badgeJob);
            this.decisionBar.Controls.Add(this.btnLock);
            this.decisionBar.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.decisionBar.Location = new System.Drawing.Point(6, 216);
            this.decisionBar.Name = "decisionBar";
            this.decisionBar.Size = new System.Drawing.Size(400, 40);
            this.decisionBar.TabIndex = 1;
            this.badgeMode.Location = new System.Drawing.Point(4, 6);
            this.badgeMode.Name = "badgeMode";
            this.badgeMode.Shape = Modern.Lab.WinForms.Controls.Display.BadgeShape.Rounded;
            this.badgeMode.Size = new System.Drawing.Size(104, 28);
            this.badgeMode.TabIndex = 0;
            this.badgeMode.Text = "-";
            this.badgeMode.Child = null;
            this.badgeJob.Location = new System.Drawing.Point(112, 6);
            this.badgeJob.Name = "badgeJob";
            this.badgeJob.Shape = Modern.Lab.WinForms.Controls.Display.BadgeShape.Rounded;
            this.badgeJob.Size = new System.Drawing.Size(80, 28);
            this.badgeJob.TabIndex = 1;
            this.badgeJob.Text = "No job";
            this.badgeJob.Child = null;
            this.btnLock.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnLock.BackColor = System.Drawing.Color.Transparent;
            this.btnLock.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnLock.IconGlyph = "";
            this.btnLock.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Subtle;
            this.btnLock.Location = new System.Drawing.Point(228, 4);
            this.btnLock.Name = "btnLock";
            this.btnLock.Size = new System.Drawing.Size(104, 32);
            this.btnLock.TabIndex = 2;
            this.btnLock.Text = "Lock";
            this.btnLock.Click += new System.EventHandler(this.OnLockClick);
            this.jobActions.ColumnCount = 3;
            this.jobActions.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.jobActions.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.jobActions.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.jobActions.Controls.Add(this.btnJobPrep, 0, 0);
            this.jobActions.Controls.Add(this.btnJobStart, 1, 0);
            this.jobActions.Controls.Add(this.btnJobEnd, 2, 0);
            this.jobActions.Dock = System.Windows.Forms.DockStyle.Fill;
            this.jobActions.Location = new System.Drawing.Point(12, 8);
            this.jobActions.Margin = new System.Windows.Forms.Padding(0);
            this.jobActions.Name = "jobActions";
            this.jobActions.Padding = new System.Windows.Forms.Padding(0, 4, 0, 0);
            this.jobActions.RowCount = 1;
            this.jobActions.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.jobActions.Size = new System.Drawing.Size(324, 40);
            this.jobActions.TabIndex = 2;
            this.gapActions.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.gapActions.Name = "gapActions";
            this.gapActions.Size = new System.Drawing.Size(1356, 8);
            this.gapJob.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.gapJob.Name = "gapJob";
            this.gapJob.Size = new System.Drawing.Size(412, 8);
            this.actionCard.Controls.Add(this.ddbPort);
            this.actionCard.Controls.Add(this.ddbEquipment);
            this.actionCard.Controls.Add(this.lblTarget);
            this.actionCard.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.actionCard.Location = new System.Drawing.Point(0, 812);
            this.actionCard.Name = "actionCard";
            this.actionCard.Padding = new System.Windows.Forms.Padding(12, 8, 12, 8);
            this.actionCard.Size = new System.Drawing.Size(1356, 56);
            this.actionCard.TabIndex = 0;
            this.lblTarget.BackColor = System.Drawing.Color.Transparent;
            this.lblTarget.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Label;
            this.lblTarget.Location = new System.Drawing.Point(12, 16);
            this.lblTarget.Name = "lblTarget";
            this.lblTarget.Size = new System.Drawing.Size(560, 24);
            this.lblTarget.TabIndex = 0;
            this.lblTarget.Text = "No equipment decided";
            this.ddbEquipment.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ddbEquipment.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Excel;
            this.ddbEquipment.Location = new System.Drawing.Point(1088, 12);
            this.ddbEquipment.Name = "ddbEquipment";
            this.ddbEquipment.Size = new System.Drawing.Size(124, 32);
            this.ddbEquipment.TabIndex = 1;
            this.ddbEquipment.Text = "Equipment";
            this.ddbEquipment.ItemClicked += new System.EventHandler<Modern.Lab.Controls.Wpf.Input.DropDownItemClickedEventArgs>(this.OnEquipmentActionClicked);
            this.ddbEquipment.Child = null;
            this.ddbPort.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.ddbPort.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Excel;
            this.ddbPort.Location = new System.Drawing.Point(1220, 12);
            this.ddbPort.Name = "ddbPort";
            this.ddbPort.Size = new System.Drawing.Size(124, 32);
            this.ddbPort.TabIndex = 5;
            this.ddbPort.Text = "Port";
            this.ddbPort.ItemClicked += new System.EventHandler<Modern.Lab.Controls.Wpf.Input.DropDownItemClickedEventArgs>(this.OnPortActionClicked);
            this.ddbPort.Child = null;
            this.jobCard.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.jobCard.Controls.Add(this.jobActions);
            this.jobCard.Location = new System.Drawing.Point(0, 812);
            this.jobCard.Name = "jobCard";
            this.jobCard.Padding = new System.Windows.Forms.Padding(12, 8, 12, 8);
            this.jobCard.Size = new System.Drawing.Size(412, 56);
            this.jobCard.TabIndex = 1;
            this.btnJobPrep.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJobPrep.BackColor = System.Drawing.Color.Transparent;
            this.btnJobPrep.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnJobPrep.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Secondary;
            this.btnJobPrep.Location = new System.Drawing.Point(4, 8);
            this.btnJobPrep.Margin = new System.Windows.Forms.Padding(4);
            this.btnJobPrep.Name = "btnJobPrep";
            this.btnJobPrep.Size = new System.Drawing.Size(125, 36);
            this.btnJobPrep.TabIndex = 2;
            this.btnJobPrep.Text = "Job Prep";
            this.btnJobPrep.Click += new System.EventHandler(this.OnJobPrepClick);
            this.btnJobStart.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJobStart.BackColor = System.Drawing.Color.Transparent;
            this.btnJobStart.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnJobStart.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Execute;
            this.btnJobStart.Location = new System.Drawing.Point(137, 8);
            this.btnJobStart.Margin = new System.Windows.Forms.Padding(4);
            this.btnJobStart.Name = "btnJobStart";
            this.btnJobStart.Size = new System.Drawing.Size(125, 36);
            this.btnJobStart.TabIndex = 3;
            this.btnJobStart.Text = "Job Start";
            this.btnJobStart.Click += new System.EventHandler(this.OnJobStartClick);
            this.btnJobEnd.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnJobEnd.BackColor = System.Drawing.Color.Transparent;
            this.btnJobEnd.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnJobEnd.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Secondary;
            this.btnJobEnd.Location = new System.Drawing.Point(270, 8);
            this.btnJobEnd.Margin = new System.Windows.Forms.Padding(4);
            this.btnJobEnd.Name = "btnJobEnd";
            this.btnJobEnd.Size = new System.Drawing.Size(126, 36);
            this.btnJobEnd.TabIndex = 4;
            this.btnJobEnd.Text = "Job End";
            this.btnJobEnd.Click += new System.EventHandler(this.OnJobEndClick);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(248)))), ((int)(((byte)(250)))));
            this.ClientSize = new System.Drawing.Size(1800, 1000);
            this.Controls.Add(this.midPanel);
            this.Controls.Add(this.gapSearch);
            this.Controls.Add(this.searchCard);
            this.Controls.Add(this.spTitle);
            this.Controls.Add(this.titlePanel);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.MinimumSize = new System.Drawing.Size(1240, 840);
            this.Name = "EquipmentLotForm";
            this.Padding = new System.Windows.Forms.Padding(12);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Equipment / Lots";
            this.Load += new System.EventHandler(this.OnFormLoad);
            this.titlePanel.ResumeLayout(false);
            this.searchCard.ResumeLayout(false);
            this.midPanel.ResumeLayout(false);
            this.splitMain.Panel1.ResumeLayout(false);
            this.splitMain.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitMain)).EndInit();
            this.splitMain.ResumeLayout(false);
            this.splitLeft.Panel1.ResumeLayout(false);
            this.splitLeft.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitLeft)).EndInit();
            this.splitLeft.ResumeLayout(false);
            this.eqpCard.ResumeLayout(false);
            this.lotCard.ResumeLayout(false);
            this.panelRequestRemark.ResumeLayout(false);
            this.tableRequestMaster.ResumeLayout(false);
            this.splitRequest.Panel1.ResumeLayout(false);
            this.splitRequest.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitRequest)).EndInit();
            this.splitRequest.ResumeLayout(false);
            this.requestCard.ResumeLayout(false);
            this.splitLotRequest.Panel1.ResumeLayout(false);
            this.splitLotRequest.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitLotRequest)).EndInit();
            this.splitLotRequest.ResumeLayout(false);
            this.durableCard.ResumeLayout(false);
            this.splitDurableDecision.Panel1.ResumeLayout(false);
            this.splitDurableDecision.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitDurableDecision)).EndInit();
            this.splitDurableDecision.ResumeLayout(false);
            this.portCard.ResumeLayout(false);
            this.decisionCard.ResumeLayout(false);
            this.jobCard.ResumeLayout(false);
            this.splitRight.Panel1.ResumeLayout(false);
            this.splitRight.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitRight)).EndInit();
            this.splitRight.ResumeLayout(false);
            this.decisionGrid.ResumeLayout(false);
            this.decisionBar.ResumeLayout(false);
            this.jobActions.ResumeLayout(false);
            this.actionCard.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel titlePanel;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblTitle;
        private System.Windows.Forms.Panel spTitle;
        private Modern.Lab.WinForms.Controls.Layout.ModernCardPanel searchCard;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblGroup;
        private Modern.Lab.WinForms.Controls.Selection.ModernComboBox cboGroup;
        private Modern.Lab.WinForms.Controls.Display.ModernStatusBadge badgeCountdown;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblInterval;
        private Modern.Lab.WinForms.Controls.Selection.ModernComboBox cboInterval;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnRefresh;
        private System.Windows.Forms.ContextMenuStrip menuEqp;
        private System.Windows.Forms.ContextMenuStrip menuPort;
        private System.Windows.Forms.ContextMenuStrip menuLot;
        private System.Windows.Forms.Panel gapSearch;
        private System.Windows.Forms.Panel midPanel;
        private Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer splitMain;
        private Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer splitLeft;
        private Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer splitLotRequest;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox eqpCard;
        private Modern.Lab.WinForms.Controls.Data.ModernDataGrid gridEqp;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox portCard;
        private Modern.Lab.WinForms.Controls.Data.ModernDataGrid gridPorts;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox lotCard;
        private Modern.Lab.WinForms.Controls.Data.ModernDataGrid gridLots;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox requestCard;
        private Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer splitRequest;
        private System.Windows.Forms.TableLayoutPanel tableRequestMaster;
        private Modern.Lab.WinForms.Controls.Display.ModernFieldList fieldRequest;
        private System.Windows.Forms.Panel panelRequestRemark;
        private System.Windows.Forms.Label lblRequestRemarkCaption;
        private System.Windows.Forms.Label lblRequestRemark;
        private System.Windows.Forms.Label lblRequestEmpty;
        private Modern.Lab.WinForms.Controls.Data.ModernDataGrid gridSpecimens;
        private Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer splitRight;
        private Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer splitDurableDecision;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox durableCard;
        private Modern.Lab.WinForms.Controls.Data.ModernDataGrid gridDurables;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox decisionCard;
        private Modern.Lab.WinForms.Controls.Display.ModernBusyOverlay decisionBusy;
        private System.Windows.Forms.TableLayoutPanel decisionGrid;
        private Modern.Lab.WinForms.Controls.Display.ModernKpiCard kpiEquipment;
        private Modern.Lab.WinForms.Controls.Display.ModernKpiCard kpiPorts;
        private Modern.Lab.WinForms.Controls.Display.ModernKpiCard kpiLot;
        private Modern.Lab.WinForms.Controls.Display.ModernKpiCard kpiDurable;
        private System.Windows.Forms.Panel decisionBar;
        private Modern.Lab.WinForms.Controls.Display.ModernStatusBadge badgeMode;
        private Modern.Lab.WinForms.Controls.Display.ModernStatusBadge badgeJob;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnLock;
        private System.Windows.Forms.TableLayoutPanel jobActions;
        private System.Windows.Forms.Panel gapActions;
        private System.Windows.Forms.Panel gapJob;
        private Modern.Lab.WinForms.Controls.Layout.ModernCardPanel actionCard;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblTarget;
        private Modern.Lab.WinForms.Controls.Input.ModernDropDownButton ddbEquipment;
        private Modern.Lab.WinForms.Controls.Input.ModernDropDownButton ddbPort;
        private Modern.Lab.WinForms.Controls.Layout.ModernCardPanel jobCard;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnJobPrep;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnJobStart;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnJobEnd;
    }
}
