namespace Modern.Lab.MasterData
{
    public partial class PfoNodeForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Panel titlePanel;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblTitle;
        private System.Windows.Forms.Panel spTitle;
        private Modern.Lab.WinForms.Controls.Layout.ModernCardPanel searchCard;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblProduct;
        private Modern.Lab.WinForms.Controls.Selection.ModernComboBox cboProduct;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnRefresh;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnCreateProductNode;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnCancel;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnSave;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnDelete;
        private System.Windows.Forms.Panel gapSearch;
        private Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer splitMain;
        private System.Windows.Forms.TableLayoutPanel paletteLayout;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox flowCard;
        private System.Windows.Forms.ListBox lstFlows;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox operCard;
        private System.Windows.Forms.ListBox lstOpers;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox structureCard;
        private System.Windows.Forms.TreeView treeNodes;
        private System.Windows.Forms.Panel statePanel;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblState;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.titlePanel = new System.Windows.Forms.Panel();
            this.lblTitle = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.spTitle = new System.Windows.Forms.Panel();
            this.searchCard = new Modern.Lab.WinForms.Controls.Layout.ModernCardPanel();
            this.lblProduct = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.cboProduct = new Modern.Lab.WinForms.Controls.Selection.ModernComboBox();
            this.btnRefresh = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.btnCreateProductNode = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.btnCancel = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.btnSave = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.btnDelete = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.gapSearch = new System.Windows.Forms.Panel();
            this.splitMain = new Modern.Lab.WinForms.Controls.Layout.ModernSplitContainer();
            this.paletteLayout = new System.Windows.Forms.TableLayoutPanel();
            this.flowCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.lstFlows = new System.Windows.Forms.ListBox();
            this.operCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.lstOpers = new System.Windows.Forms.ListBox();
            this.structureCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.treeNodes = new System.Windows.Forms.TreeView();
            this.statePanel = new System.Windows.Forms.Panel();
            this.lblState = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.titlePanel.SuspendLayout();
            this.searchCard.SuspendLayout();
            this.splitMain.Panel1.SuspendLayout();
            this.splitMain.Panel2.SuspendLayout();
            this.splitMain.SuspendLayout();
            this.paletteLayout.SuspendLayout();
            this.flowCard.SuspendLayout();
            this.operCard.SuspendLayout();
            this.structureCard.SuspendLayout();
            this.statePanel.SuspendLayout();
            this.SuspendLayout();
            this.titlePanel.Controls.Add(this.lblTitle);
            this.titlePanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.titlePanel.Location = new System.Drawing.Point(12, 12);
            this.titlePanel.Name = "titlePanel";
            this.titlePanel.Size = new System.Drawing.Size(1176, 28);
            this.titlePanel.TabIndex = 0;
            this.lblTitle.BackColor = System.Drawing.Color.Transparent;
            this.lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitle.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Title;
            this.lblTitle.Location = new System.Drawing.Point(0, 0);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(1176, 28);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "PFO Node";
            this.lblTitle.TitleBar = true;
            this.spTitle.Dock = System.Windows.Forms.DockStyle.Top;
            this.spTitle.Location = new System.Drawing.Point(12, 40);
            this.spTitle.Name = "spTitle";
            this.spTitle.Size = new System.Drawing.Size(1176, 8);
            this.spTitle.TabIndex = 1;
            this.searchCard.Controls.Add(this.lblProduct);
            this.searchCard.Controls.Add(this.cboProduct);
            this.searchCard.Controls.Add(this.btnRefresh);
            this.searchCard.Controls.Add(this.btnCreateProductNode);
            this.searchCard.Controls.Add(this.btnCancel);
            this.searchCard.Controls.Add(this.btnSave);
            this.searchCard.Controls.Add(this.btnDelete);
            this.searchCard.Dock = System.Windows.Forms.DockStyle.Top;
            this.searchCard.Location = new System.Drawing.Point(12, 48);
            this.searchCard.Name = "searchCard";
            this.searchCard.Padding = new System.Windows.Forms.Padding(12, 8, 12, 8);
            this.searchCard.Size = new System.Drawing.Size(1176, 56);
            this.searchCard.TabIndex = 2;
            this.lblProduct.BackColor = System.Drawing.Color.Transparent;
            this.lblProduct.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Label;
            this.lblProduct.Location = new System.Drawing.Point(12, 12);
            this.lblProduct.Name = "lblProduct";
            this.lblProduct.Size = new System.Drawing.Size(72, 32);
            this.lblProduct.TabIndex = 0;
            this.lblProduct.Text = "Product";
            this.cboProduct.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboProduct.Location = new System.Drawing.Point(88, 12);
            this.cboProduct.Name = "cboProduct";
            this.cboProduct.Size = new System.Drawing.Size(360, 32);
            this.cboProduct.TabIndex = 1;
            this.cboProduct.SelectedIndexChanged += new System.EventHandler(this.OnProductChanged);
            this.btnRefresh.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Primary;
            this.btnRefresh.Location = new System.Drawing.Point(456, 12);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.Size = new System.Drawing.Size(104, 32);
            this.btnRefresh.TabIndex = 2;
            this.btnRefresh.Text = "Refresh";
            this.btnRefresh.Click += new System.EventHandler(this.OnRefreshClick);
            this.btnCreateProductNode.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Execute;
            this.btnCreateProductNode.Location = new System.Drawing.Point(568, 12);
            this.btnCreateProductNode.Name = "btnCreateProductNode";
            this.btnCreateProductNode.Size = new System.Drawing.Size(176, 32);
            this.btnCreateProductNode.TabIndex = 3;
            this.btnCreateProductNode.Text = "Create Product Node";
            this.btnCreateProductNode.Visible = false;
            this.btnCreateProductNode.Click += new System.EventHandler(this.OnCreateProductNodeClick);
            this.btnCancel.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Secondary;
            this.btnCancel.Location = new System.Drawing.Point(752, 12);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(88, 32);
            this.btnCancel.TabIndex = 4;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.Click += new System.EventHandler(this.OnCancelClick);
            this.btnSave.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Execute;
            this.btnSave.Location = new System.Drawing.Point(848, 12);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(88, 32);
            this.btnSave.TabIndex = 5;
            this.btnSave.Text = "Save";
            this.btnSave.Click += new System.EventHandler(this.OnSaveClick);
            this.btnDelete.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Danger;
            this.btnDelete.Location = new System.Drawing.Point(944, 12);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new System.Drawing.Size(88, 32);
            this.btnDelete.TabIndex = 6;
            this.btnDelete.Text = "Delete";
            this.btnDelete.Click += new System.EventHandler(this.OnDeleteClick);
            this.gapSearch.Dock = System.Windows.Forms.DockStyle.Top;
            this.gapSearch.Location = new System.Drawing.Point(12, 104);
            this.gapSearch.Name = "gapSearch";
            this.gapSearch.Size = new System.Drawing.Size(1176, 8);
            this.gapSearch.TabIndex = 3;
            this.splitMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitMain.KeepRatio = true;
            this.splitMain.Location = new System.Drawing.Point(12, 112);
            this.splitMain.Name = "splitMain";
            this.splitMain.Panel1.Controls.Add(this.paletteLayout);
            this.splitMain.Panel2.Controls.Add(this.structureCard);
            this.splitMain.Size = new System.Drawing.Size(1176, 616);
            this.splitMain.SplitterDistance = 420;
            this.splitMain.SplitterWidth = 8;
            this.splitMain.TabIndex = 4;
            this.splitMain.TabStop = false;
            this.paletteLayout.ColumnCount = 1;
            this.paletteLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.paletteLayout.Controls.Add(this.flowCard, 0, 0);
            this.paletteLayout.Controls.Add(this.operCard, 0, 1);
            this.paletteLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.paletteLayout.Location = new System.Drawing.Point(0, 0);
            this.paletteLayout.Name = "paletteLayout";
            this.paletteLayout.RowCount = 2;
            this.paletteLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.paletteLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.paletteLayout.Size = new System.Drawing.Size(420, 616);
            this.paletteLayout.TabIndex = 0;
            this.flowCard.Controls.Add(this.lstFlows);
            this.flowCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowCard.Location = new System.Drawing.Point(0, 0);
            this.flowCard.Margin = new System.Windows.Forms.Padding(0, 0, 0, 4);
            this.flowCard.Name = "flowCard";
            this.flowCard.Padding = new System.Windows.Forms.Padding(8, 40, 8, 8);
            this.flowCard.Size = new System.Drawing.Size(420, 304);
            this.flowCard.TabIndex = 0;
            this.flowCard.Text = "Available Flows — drag onto Product";
            this.flowCard.TitleBar = true;
            this.lstFlows.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstFlows.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lstFlows.DrawMode = System.Windows.Forms.DrawMode.Normal;
            this.lstFlows.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lstFlows.IntegralHeight = false;
            this.lstFlows.ItemHeight = 22;
            this.lstFlows.Location = new System.Drawing.Point(10, 40);
            this.lstFlows.Name = "lstFlows";
            this.lstFlows.Size = new System.Drawing.Size(400, 254);
            this.lstFlows.TabIndex = 0;
            this.lstFlows.MouseDown += new System.Windows.Forms.MouseEventHandler(this.OnFlowMouseDown);
            this.operCard.Controls.Add(this.lstOpers);
            this.operCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.operCard.Location = new System.Drawing.Point(0, 312);
            this.operCard.Margin = new System.Windows.Forms.Padding(0, 4, 0, 0);
            this.operCard.Name = "operCard";
            this.operCard.Padding = new System.Windows.Forms.Padding(8, 40, 8, 8);
            this.operCard.Size = new System.Drawing.Size(420, 304);
            this.operCard.TabIndex = 1;
            this.operCard.Text = "Available Opers — drag onto Flow";
            this.operCard.TitleBar = true;
            this.lstOpers.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.lstOpers.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lstOpers.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.lstOpers.IntegralHeight = false;
            this.lstOpers.ItemHeight = 22;
            this.lstOpers.Location = new System.Drawing.Point(10, 40);
            this.lstOpers.Name = "lstOpers";
            this.lstOpers.Size = new System.Drawing.Size(400, 254);
            this.lstOpers.TabIndex = 0;
            this.lstOpers.MouseDown += new System.Windows.Forms.MouseEventHandler(this.OnOperMouseDown);
            this.structureCard.Controls.Add(this.treeNodes);
            this.structureCard.Controls.Add(this.statePanel);
            this.structureCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.structureCard.Location = new System.Drawing.Point(0, 0);
            this.structureCard.Name = "structureCard";
            this.structureCard.Padding = new System.Windows.Forms.Padding(8, 40, 8, 8);
            this.structureCard.Size = new System.Drawing.Size(748, 616);
            this.structureCard.TabIndex = 0;
            this.structureCard.Text = "Product → Flow → Oper";
            this.structureCard.TitleBar = true;
            this.treeNodes.AllowDrop = true;
            this.treeNodes.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.treeNodes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treeNodes.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.treeNodes.FullRowSelect = true;
            this.treeNodes.HideSelection = false;
            this.treeNodes.Indent = 24;
            this.treeNodes.ItemHeight = 28;
            this.treeNodes.Location = new System.Drawing.Point(10, 40);
            this.treeNodes.Name = "treeNodes";
            this.treeNodes.ShowLines = true;
            this.treeNodes.ShowNodeToolTips = true;
            this.treeNodes.Size = new System.Drawing.Size(728, 520);
            this.treeNodes.TabIndex = 0;
            this.treeNodes.ItemDrag += new System.Windows.Forms.ItemDragEventHandler(this.OnTreeItemDrag);
            this.treeNodes.DragOver += new System.Windows.Forms.DragEventHandler(this.OnTreeDragOver);
            this.treeNodes.DragDrop += new System.Windows.Forms.DragEventHandler(this.OnTreeDragDrop);
            this.treeNodes.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.OnTreeAfterSelect);
            this.statePanel.Controls.Add(this.lblState);
            this.statePanel.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.statePanel.Location = new System.Drawing.Point(10, 560);
            this.statePanel.Name = "statePanel";
            this.statePanel.Padding = new System.Windows.Forms.Padding(4, 8, 4, 0);
            this.statePanel.Size = new System.Drawing.Size(728, 46);
            this.statePanel.TabIndex = 1;
            this.lblState.BackColor = System.Drawing.Color.Transparent;
            this.lblState.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblState.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Helper;
            this.lblState.Location = new System.Drawing.Point(4, 8);
            this.lblState.Name = "lblState";
            this.lblState.Size = new System.Drawing.Size(720, 38);
            this.lblState.TabIndex = 0;
            this.lblState.Text = "Loading PFO structure…";
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1200, 740);
            this.Controls.Add(this.splitMain);
            this.Controls.Add(this.gapSearch);
            this.Controls.Add(this.searchCard);
            this.Controls.Add(this.spTitle);
            this.Controls.Add(this.titlePanel);
            this.MinimumSize = new System.Drawing.Size(960, 620);
            this.Name = "PfoNodeForm";
            this.Padding = new System.Windows.Forms.Padding(12);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "PFO Node";
            this.Load += new System.EventHandler(this.OnFormLoad);
            this.titlePanel.ResumeLayout(false);
            this.searchCard.ResumeLayout(false);
            this.splitMain.Panel1.ResumeLayout(false);
            this.splitMain.Panel2.ResumeLayout(false);
            this.splitMain.ResumeLayout(false);
            this.paletteLayout.ResumeLayout(false);
            this.flowCard.ResumeLayout(false);
            this.operCard.ResumeLayout(false);
            this.structureCard.ResumeLayout(false);
            this.statePanel.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
