namespace Modern.Lab.Samples
{
    public partial class CarrierEditForm
    {

        private System.ComponentModel.IContainer components = null;



        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code





        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.moveMenu = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.miMoveSelRight = new System.Windows.Forms.ToolStripMenuItem();
            this.miMoveAllRight = new System.Windows.Forms.ToolStripMenuItem();
            this.miMoveSelLeft = new System.Windows.Forms.ToolStripMenuItem();
            this.miMoveAllLeft = new System.Windows.Forms.ToolStripMenuItem();
            this.titlePanel = new System.Windows.Forms.Panel();
            this.lblTitle = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.badgeEnv = new Modern.Lab.WinForms.Controls.Display.ModernStatusBadge();
            this.spTitle = new System.Windows.Forms.Panel();
            this.searchCard = new Modern.Lab.WinForms.Controls.Layout.ModernCardPanel();
            this.lblType = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.cboType = new Modern.Lab.WinForms.Controls.Selection.ModernComboBox();
            this.lblCarrier = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.cboSource = new Modern.Lab.WinForms.Controls.Selection.ModernComboBox();
            this.btnRefresh = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.gapSearch = new System.Windows.Forms.Panel();
            this.midPanel = new System.Windows.Forms.Panel();
            this.tableMid = new System.Windows.Forms.TableLayoutPanel();
            this.sourceCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.mapSource = new Modern.Lab.WinForms.Controls.Display.ModernSlotMap();
            this.barSource = new Modern.Lab.WinForms.Controls.Display.ModernProgressBar();
            this.centerPanel = new System.Windows.Forms.Panel();
            this.lblTransfer = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.lblTransferHint = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.btnAllRight = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.btnSelRight = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.btnSelLeft = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.btnAllLeft = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.badgeSourceLot = new Modern.Lab.WinForms.Controls.Display.ModernStatusBadge();
            this.targetCard = new Modern.Lab.WinForms.Controls.Layout.ModernGroupBox();
            this.mapTarget = new Modern.Lab.WinForms.Controls.Display.ModernSlotMap();
            this.barTarget = new Modern.Lab.WinForms.Controls.Display.ModernProgressBar();
            this.badgeTargetLot = new Modern.Lab.WinForms.Controls.Display.ModernStatusBadge();
            this.lblTarget = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.cboTarget = new Modern.Lab.WinForms.Controls.Selection.ModernComboBox();
            this.lblDescription = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.txtDescription = new Modern.Lab.WinForms.Controls.Input.ModernTextBox();
            this.gapBottom = new System.Windows.Forms.Panel();
            this.bottomPanel = new System.Windows.Forms.Panel();
            this.actionCard = new Modern.Lab.WinForms.Controls.Layout.ModernCardPanel();
            this.lblActionStatus = new Modern.Lab.WinForms.Controls.Display.ModernLabel();
            this.btnMove = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.btnScrap = new Modern.Lab.WinForms.Controls.Input.ModernButton();
            this.tipLots = new System.Windows.Forms.ToolTip(this.components);
            this.titlePanel.SuspendLayout();
            this.searchCard.SuspendLayout();
            this.midPanel.SuspendLayout();
            this.tableMid.SuspendLayout();
            this.sourceCard.SuspendLayout();
            this.centerPanel.SuspendLayout();
            this.targetCard.SuspendLayout();
            this.bottomPanel.SuspendLayout();
            this.actionCard.SuspendLayout();
            this.SuspendLayout();
            this.titlePanel.Controls.Add(this.lblTitle);
            this.titlePanel.Controls.Add(this.badgeEnv);
            this.titlePanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.titlePanel.Location = new System.Drawing.Point(12, 12);
            this.titlePanel.Name = "titlePanel";
            this.titlePanel.Size = new System.Drawing.Size(1516, 28);
            this.titlePanel.TabIndex = 0;
            this.lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitle.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Title;
            this.lblTitle.Location = new System.Drawing.Point(0, 0);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(1456, 28);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Carrier Editor";
            this.lblTitle.TitleBar = true;
            this.lblTitle.Child = null;
            this.badgeEnv.Semantic = Modern.Lab.Theming.SemanticKind.Info;
            this.badgeEnv.Shape = Modern.Lab.WinForms.Controls.Display.BadgeShape.Rounded;
            this.badgeEnv.Dock = System.Windows.Forms.DockStyle.Right;
            this.badgeEnv.Location = new System.Drawing.Point(1456, 0);
            this.badgeEnv.Name = "badgeEnv";
            this.badgeEnv.Size = new System.Drawing.Size(60, 28);
            this.badgeEnv.TabIndex = 1;
            this.badgeEnv.Text = "AOS";
            this.badgeEnv.Child = null;
            this.spTitle.Dock = System.Windows.Forms.DockStyle.Top;
            this.spTitle.Location = new System.Drawing.Point(12, 40);
            this.spTitle.Name = "spTitle";
            this.spTitle.Size = new System.Drawing.Size(1516, 8);
            this.spTitle.TabIndex = 1;
            this.searchCard.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.searchCard.Controls.Add(this.lblType);
            this.searchCard.Controls.Add(this.cboType);
            this.searchCard.Controls.Add(this.lblCarrier);
            this.searchCard.Controls.Add(this.cboSource);
            this.searchCard.Controls.Add(this.lblTarget);
            this.searchCard.Controls.Add(this.cboTarget);
            this.searchCard.Controls.Add(this.lblDescription);
            this.searchCard.Controls.Add(this.txtDescription);
            this.searchCard.Controls.Add(this.btnRefresh);
            this.searchCard.Dock = System.Windows.Forms.DockStyle.Top;
            this.searchCard.Location = new System.Drawing.Point(12, 48);
            this.searchCard.Name = "searchCard";
            this.searchCard.Padding = new System.Windows.Forms.Padding(12, 8, 12, 8);
            this.searchCard.Size = new System.Drawing.Size(1516, 72);
            this.searchCard.TabIndex = 2;
            this.lblType.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Label;
            this.lblType.Location = new System.Drawing.Point(12, 8);
            this.lblType.Name = "lblType";
            this.lblType.Size = new System.Drawing.Size(120, 18);
            this.lblType.TabIndex = 0;
            this.lblType.Text = "Carrier type";
            this.lblType.Child = null;
            this.cboType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboType.Location = new System.Drawing.Point(12, 32);
            this.cboType.Name = "cboType";
            this.cboType.Size = new System.Drawing.Size(120, 32);
            this.cboType.TabIndex = 1;
            this.cboType.SelectedIndexChanged += new System.EventHandler(this.OnTypeChanged);
            this.cboType.Child = null;
            this.lblCarrier.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Label;
            this.lblCarrier.Location = new System.Drawing.Point(156, 8);
            this.lblCarrier.Name = "lblCarrier";
            this.lblCarrier.Size = new System.Drawing.Size(190, 18);
            this.lblCarrier.TabIndex = 2;
            this.lblCarrier.Text = "Source carrier";
            this.lblCarrier.Child = null;
            this.cboSource.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboSource.Location = new System.Drawing.Point(156, 32);
            this.cboSource.Name = "cboSource";
            this.cboSource.Size = new System.Drawing.Size(190, 32);
            this.cboSource.TabIndex = 3;
            this.cboSource.SelectedIndexChanged += new System.EventHandler(this.OnSourceChanged);
            this.cboSource.Child = null;
            this.lblTarget.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Label;
            this.lblTarget.Location = new System.Drawing.Point(366, 8);
            this.lblTarget.Name = "lblTarget";
            this.lblTarget.Size = new System.Drawing.Size(190, 18);
            this.lblTarget.TabIndex = 4;
            this.lblTarget.Text = "Target carrier";
            this.lblTarget.Child = null;
            this.cboTarget.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTarget.Location = new System.Drawing.Point(366, 32);
            this.cboTarget.Name = "cboTarget";
            this.cboTarget.Size = new System.Drawing.Size(190, 32);
            this.cboTarget.TabIndex = 5;
            this.cboTarget.SelectedIndexChanged += new System.EventHandler(this.OnTargetChanged);
            this.cboTarget.Child = null;
            this.lblDescription.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Label;
            this.lblDescription.Location = new System.Drawing.Point(572, 8);
            this.lblDescription.Name = "lblDescription";
            this.lblDescription.Size = new System.Drawing.Size(820, 18);
            this.lblDescription.TabIndex = 6;
            this.lblDescription.Text = "Description";
            this.lblDescription.Child = null;
            this.txtDescription.Location = new System.Drawing.Point(572, 32);
            this.txtDescription.MaxLength = 200;
            this.txtDescription.Name = "txtDescription";
            this.txtDescription.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this.txtDescription.Size = new System.Drawing.Size(820, 32);
            this.txtDescription.TabIndex = 7;
            this.txtDescription.Child = null;
            this.btnRefresh.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnRefresh.Location = new System.Drawing.Point(1424, 20);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.Size = new System.Drawing.Size(80, 32);
            this.btnRefresh.TabIndex = 4;
            this.btnRefresh.Text = "↻";
            this.btnRefresh.TopLabel = "Refresh";
            this.btnRefresh.Click += new System.EventHandler(this.OnRefreshClick);
            this.btnRefresh.Child = null;
            this.gapSearch.Dock = System.Windows.Forms.DockStyle.Top;
            this.gapSearch.Location = new System.Drawing.Point(12, 120);
            this.gapSearch.Name = "gapSearch";
            this.gapSearch.Size = new System.Drawing.Size(1516, 8);
            this.gapSearch.TabIndex = 3;
            this.midPanel.Controls.Add(this.tableMid);
            this.midPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.midPanel.Location = new System.Drawing.Point(12, 128);
            this.midPanel.Name = "midPanel";
            this.midPanel.Size = new System.Drawing.Size(1516, 660);
            this.midPanel.TabIndex = 4;
            this.tableMid.ColumnCount = 3;
            this.tableMid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableMid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 96F));
            this.tableMid.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableMid.Controls.Add(this.sourceCard, 0, 0);
            this.tableMid.Controls.Add(this.centerPanel, 1, 0);
            this.tableMid.Controls.Add(this.targetCard, 2, 0);
            this.tableMid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableMid.Location = new System.Drawing.Point(0, 0);
            this.tableMid.Name = "tableMid";
            this.tableMid.RowCount = 1;
            this.tableMid.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableMid.Size = new System.Drawing.Size(1516, 660);
            this.tableMid.TabIndex = 0;
            this.sourceCard.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.sourceCard.Controls.Add(this.badgeSourceLot);
            this.sourceCard.Controls.Add(this.mapSource);
            this.sourceCard.Controls.Add(this.barSource);
            this.sourceCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sourceCard.Location = new System.Drawing.Point(0, 0);
            this.sourceCard.Name = "sourceCard";
            this.sourceCard.Padding = new System.Windows.Forms.Padding(8, 40, 8, 8);
            this.sourceCard.Size = new System.Drawing.Size(668, 660);
            this.sourceCard.TabIndex = 0;
            this.sourceCard.Text = "Source carrier";
            this.sourceCard.TitleAccent = false;
            this.badgeSourceLot.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.badgeSourceLot.Color = "#DBEAFE";
            this.badgeSourceLot.Location = new System.Drawing.Point(120, 4);
            this.badgeSourceLot.Name = "badgeSourceLot";
            this.badgeSourceLot.Shape = Modern.Lab.WinForms.Controls.Display.BadgeShape.Rounded;
            this.badgeSourceLot.Size = new System.Drawing.Size(116, 24);
            this.badgeSourceLot.TabIndex = 1;
            this.badgeSourceLot.Text = "-";
            this.badgeSourceLot.Child = null;
            this.barSource.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.barSource.Name = "barSource";
            this.barSource.Size = new System.Drawing.Size(652, 14);
            this.barSource.ShowText = true;
            this.barSource.Maximum = 0;
            this.barSource.TabIndex = 2;
            this.barSource.Child = null;
            this.mapSource.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mapSource.EnableDragOut = false;
            this.mapSource.Location = new System.Drawing.Point(8, 40);
            this.mapSource.Name = "mapSource";
            this.mapSource.Size = new System.Drawing.Size(652, 612);
            this.mapSource.TabIndex = 0;
            this.mapSource.CellClicked += new System.EventHandler<Modern.Lab.Controls.Wpf.Display.SlotMapCellEventArgs>(this.OnSourceCellClicked);
            this.mapSource.CellRightClick += new System.EventHandler<Modern.Lab.Controls.Wpf.Display.SlotMapCellEventArgs>(this.OnSourceCellRightClick);
            this.mapSource.Child = null;
            this.centerPanel.Controls.Add(this.lblTransfer);
            this.centerPanel.Controls.Add(this.lblTransferHint);
            this.centerPanel.Controls.Add(this.btnAllRight);
            this.centerPanel.Controls.Add(this.btnSelRight);
            this.centerPanel.Controls.Add(this.btnSelLeft);
            this.centerPanel.Controls.Add(this.btnAllLeft);
            this.centerPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.centerPanel.Location = new System.Drawing.Point(668, 0);
            this.centerPanel.Name = "centerPanel";
            this.centerPanel.Size = new System.Drawing.Size(96, 660);
            this.centerPanel.TabIndex = 1;
            this.lblTransfer.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Label;
            this.lblTransfer.Location = new System.Drawing.Point(8, 218);
            this.lblTransfer.Name = "lblTransfer";
            this.lblTransfer.Size = new System.Drawing.Size(80, 18);
            this.lblTransfer.TabIndex = 0;
            this.lblTransfer.Text = "PLAN";
            this.lblTransfer.Child = null;
            this.lblTransferHint.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Helper;
            this.lblTransferHint.Location = new System.Drawing.Point(8, 238);
            this.lblTransferHint.Name = "lblTransferHint";
            this.lblTransferHint.Size = new System.Drawing.Size(80, 18);
            this.lblTransferHint.TabIndex = 1;
            this.lblTransferHint.Text = "stage";
            this.lblTransferHint.Child = null;
            this.btnAllRight.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnAllRight.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Secondary;
            this.btnAllRight.GlyphSize = 20D;
            this.btnAllRight.TopLabel = "All";
            this.btnAllRight.Location = new System.Drawing.Point(24, 264);
            this.btnAllRight.Name = "btnAllRight";
            this.btnAllRight.Size = new System.Drawing.Size(48, 44);
            this.btnAllRight.TabIndex = 2;
            this.btnAllRight.Text = "»";
            this.btnAllRight.Click += new System.EventHandler(this.OnMoveAllRight);
            this.btnAllRight.Child = null;
            this.btnSelRight.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnSelRight.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Secondary;
            this.btnSelRight.GlyphSize = 20D;
            this.btnSelRight.TopLabel = "Selected";
            this.btnSelRight.Location = new System.Drawing.Point(24, 312);
            this.btnSelRight.Name = "btnSelRight";
            this.btnSelRight.Size = new System.Drawing.Size(48, 44);
            this.btnSelRight.TabIndex = 3;
            this.btnSelRight.Text = "›";
            this.btnSelRight.Click += new System.EventHandler(this.OnMoveSelRight);
            this.btnSelRight.Child = null;
            this.btnSelLeft.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnSelLeft.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Secondary;
            this.btnSelLeft.GlyphSize = 20D;
            this.btnSelLeft.TopLabel = "Selected";
            this.btnSelLeft.Location = new System.Drawing.Point(24, 376);
            this.btnSelLeft.Name = "btnSelLeft";
            this.btnSelLeft.Size = new System.Drawing.Size(48, 44);
            this.btnSelLeft.TabIndex = 4;
            this.btnSelLeft.Text = "‹";
            this.btnSelLeft.Click += new System.EventHandler(this.OnMoveSelLeft);
            this.btnSelLeft.Child = null;
            this.btnAllLeft.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnAllLeft.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Secondary;
            this.btnAllLeft.GlyphSize = 20D;
            this.btnAllLeft.TopLabel = "All";
            this.btnAllLeft.Location = new System.Drawing.Point(24, 424);
            this.btnAllLeft.Name = "btnAllLeft";
            this.btnAllLeft.Size = new System.Drawing.Size(48, 44);
            this.btnAllLeft.TabIndex = 5;
            this.btnAllLeft.Text = "«";
            this.btnAllLeft.Click += new System.EventHandler(this.OnMoveAllLeft);
            this.btnAllLeft.Child = null;
            this.targetCard.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.targetCard.Controls.Add(this.badgeTargetLot);
            this.targetCard.Controls.Add(this.mapTarget);
            this.targetCard.Controls.Add(this.barTarget);
            this.targetCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.targetCard.Location = new System.Drawing.Point(764, 0);
            this.targetCard.Name = "targetCard";
            this.targetCard.Padding = new System.Windows.Forms.Padding(8, 40, 8, 8);
            this.targetCard.Size = new System.Drawing.Size(668, 660);
            this.targetCard.TabIndex = 2;
            this.targetCard.Text = "Target carrier";
            this.targetCard.TitleAccent = false;
            this.barTarget.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.barTarget.Name = "barTarget";
            this.barTarget.Size = new System.Drawing.Size(652, 14);
            this.barTarget.ShowText = true;
            this.barTarget.Maximum = 0;
            this.barTarget.TabIndex = 2;
            this.barTarget.Child = null;
            this.mapTarget.AcceptDrops = false;
            this.mapTarget.AllowSelection = true;
            this.mapTarget.Dock = System.Windows.Forms.DockStyle.Fill;
            this.mapTarget.Location = new System.Drawing.Point(8, 40);
            this.mapTarget.Name = "mapTarget";
            this.mapTarget.Size = new System.Drawing.Size(652, 612);
            this.mapTarget.TabIndex = 0;
            this.mapTarget.CellClicked += new System.EventHandler<Modern.Lab.Controls.Wpf.Display.SlotMapCellEventArgs>(this.OnTargetCellClicked);
            this.mapTarget.CellRightClick += new System.EventHandler<Modern.Lab.Controls.Wpf.Display.SlotMapCellEventArgs>(this.OnTargetCellRightClick);
            this.mapTarget.Child = null;
            this.badgeTargetLot.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.badgeTargetLot.Color = "#DBEAFE";
            this.badgeTargetLot.Location = new System.Drawing.Point(120, 4);
            this.badgeTargetLot.Name = "badgeTargetLot";
            this.badgeTargetLot.Shape = Modern.Lab.WinForms.Controls.Display.BadgeShape.Rounded;
            this.badgeTargetLot.Size = new System.Drawing.Size(116, 24);
            this.badgeTargetLot.TabIndex = 1;
            this.badgeTargetLot.Text = "-";
            this.badgeTargetLot.Child = null;
            this.gapBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.gapBottom.Location = new System.Drawing.Point(12, 732);
            this.gapBottom.Name = "gapBottom";
            this.gapBottom.Size = new System.Drawing.Size(1516, 8);
            this.gapBottom.TabIndex = 6;
            this.bottomPanel.Controls.Add(this.actionCard);
            this.bottomPanel.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bottomPanel.Location = new System.Drawing.Point(12, 740);
            this.bottomPanel.Name = "bottomPanel";
            this.bottomPanel.Size = new System.Drawing.Size(1516, 56);
            this.bottomPanel.TabIndex = 7;
            this.actionCard.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.actionCard.Controls.Add(this.lblActionStatus);
            this.actionCard.Controls.Add(this.btnMove);
            this.actionCard.Controls.Add(this.btnScrap);
            this.actionCard.Dock = System.Windows.Forms.DockStyle.Fill;
            this.actionCard.Location = new System.Drawing.Point(0, 0);
            this.actionCard.Name = "actionCard";
            this.actionCard.Size = new System.Drawing.Size(1516, 56);
            this.actionCard.TabIndex = 0;
            this.lblActionStatus.Kind = Modern.Lab.Controls.Wpf.Display.LabelKind.Helper;
            this.lblActionStatus.Location = new System.Drawing.Point(12, 16);
            this.lblActionStatus.Name = "lblActionStatus";
            this.lblActionStatus.Size = new System.Drawing.Size(940, 24);
            this.lblActionStatus.TabIndex = 0;
            this.lblActionStatus.Text = "Select one or more source wafers, then stage with › or ».";
            this.lblActionStatus.Child = null;
            this.btnMove.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Execute;
            this.btnMove.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnMove.Location = new System.Drawing.Point(1336, 12);
            this.btnMove.Name = "btnMove";
            this.btnMove.Size = new System.Drawing.Size(80, 32);
            this.btnMove.TabIndex = 1;
            this.btnMove.Text = "Move";
            this.btnMove.Click += new System.EventHandler(this.OnMoveClick);
            this.btnMove.Child = null;
            this.btnScrap.Kind = Modern.Lab.Controls.Wpf.Input.ButtonKind.Danger;
            this.btnScrap.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnScrap.Location = new System.Drawing.Point(1424, 12);
            this.btnScrap.Name = "btnScrap";
            this.btnScrap.Size = new System.Drawing.Size(80, 32);
            this.btnScrap.TabIndex = 3;
            this.btnScrap.Text = "Scrap";
            this.btnScrap.Click += new System.EventHandler(this.OnScrapClick);
            this.btnScrap.Child = null;
            this.moveMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
                this.miMoveSelRight,
                this.miMoveAllRight,
                this.miMoveSelLeft,
                this.miMoveAllLeft});
            this.moveMenu.Name = "moveMenu";
            this.miMoveSelRight.Name = "miMoveSelRight";
            this.miMoveSelRight.Text = "Stage Selected  ›";
            this.miMoveSelRight.Click += new System.EventHandler(this.OnMoveSelRight);
            this.miMoveAllRight.Name = "miMoveAllRight";
            this.miMoveAllRight.Text = "Stage All  »";
            this.miMoveAllRight.Click += new System.EventHandler(this.OnMoveAllRight);
            this.miMoveSelLeft.Name = "miMoveSelLeft";
            this.miMoveSelLeft.Text = "Unstage Selected  ‹";
            this.miMoveSelLeft.Click += new System.EventHandler(this.OnMoveSelLeft);
            this.miMoveAllLeft.Name = "miMoveAllLeft";
            this.miMoveAllLeft.Text = "Unstage All  «";
            this.miMoveAllLeft.Click += new System.EventHandler(this.OnMoveAllLeft);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(247)))), ((int)(((byte)(248)))), ((int)(((byte)(250)))));
            this.ClientSize = new System.Drawing.Size(1540, 800);
            this.Controls.Add(this.midPanel);
            this.Controls.Add(this.gapBottom);
            this.Controls.Add(this.bottomPanel);
            this.Controls.Add(this.gapSearch);
            this.Controls.Add(this.searchCard);
            this.Controls.Add(this.spTitle);
            this.Controls.Add(this.titlePanel);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.MinimumSize = new System.Drawing.Size(1240, 660);
            this.Name = "CarrierEditForm";
            this.Padding = new System.Windows.Forms.Padding(12);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Carrier Editor";
            this.Load += new System.EventHandler(this.OnFormLoad);
            this.titlePanel.ResumeLayout(false);
            this.searchCard.ResumeLayout(false);
            this.midPanel.ResumeLayout(false);
            this.tableMid.ResumeLayout(false);
            this.sourceCard.ResumeLayout(false);
            this.centerPanel.ResumeLayout(false);
            this.targetCard.ResumeLayout(false);
            this.bottomPanel.ResumeLayout(false);
            this.actionCard.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel titlePanel;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblTitle;
        private Modern.Lab.WinForms.Controls.Display.ModernStatusBadge badgeEnv;
        private System.Windows.Forms.Panel spTitle;
        private Modern.Lab.WinForms.Controls.Layout.ModernCardPanel searchCard;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblType;
        private Modern.Lab.WinForms.Controls.Selection.ModernComboBox cboType;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblCarrier;
        private Modern.Lab.WinForms.Controls.Selection.ModernComboBox cboSource;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnRefresh;
        private System.Windows.Forms.Panel gapSearch;
        private System.Windows.Forms.Panel midPanel;
        private System.Windows.Forms.TableLayoutPanel tableMid;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox sourceCard;
        private Modern.Lab.WinForms.Controls.Display.ModernSlotMap mapSource;
        private Modern.Lab.WinForms.Controls.Display.ModernProgressBar barSource;
        private System.Windows.Forms.Panel centerPanel;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblTransfer;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblTransferHint;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnAllRight;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnSelRight;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnSelLeft;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnAllLeft;
        private Modern.Lab.WinForms.Controls.Display.ModernStatusBadge badgeSourceLot;
        private Modern.Lab.WinForms.Controls.Display.ModernStatusBadge badgeTargetLot;
        private System.Windows.Forms.Panel gapBottom;
        private System.Windows.Forms.Panel bottomPanel;
        private Modern.Lab.WinForms.Controls.Layout.ModernCardPanel actionCard;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblActionStatus;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnMove;
        private Modern.Lab.WinForms.Controls.Input.ModernButton btnScrap;
        private Modern.Lab.WinForms.Controls.Layout.ModernGroupBox targetCard;
        private Modern.Lab.WinForms.Controls.Display.ModernSlotMap mapTarget;
        private Modern.Lab.WinForms.Controls.Display.ModernProgressBar barTarget;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblTarget;
        private Modern.Lab.WinForms.Controls.Selection.ModernComboBox cboTarget;
        private Modern.Lab.WinForms.Controls.Display.ModernLabel lblDescription;
        private Modern.Lab.WinForms.Controls.Input.ModernTextBox txtDescription;
        private System.Windows.Forms.ToolTip tipLots;
        private System.Windows.Forms.ContextMenuStrip moveMenu;
        private System.Windows.Forms.ToolStripMenuItem miMoveSelRight;
        private System.Windows.Forms.ToolStripMenuItem miMoveAllRight;
        private System.Windows.Forms.ToolStripMenuItem miMoveSelLeft;
        private System.Windows.Forms.ToolStripMenuItem miMoveAllLeft;
    }
}
